# Generated by Django 3.2.12 on 2022-03-16 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycookbook', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycookbook.recipe')),
            ],
        ),
    ]
