# Generated by Django 3.2.12 on 2022-03-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycookbook', '0004_myrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='show_hide',
            field=models.BooleanField(default=False),
        ),
    ]
