# Generated by Django 3.2.12 on 2022-03-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycookbook', '0007_recipe_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='show_hide',
        ),
    ]
