# Generated by Django 3.2.12 on 2022-03-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycookbook', '0008_remove_recipe_show_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='liked',
            field=models.IntegerField(default=0),
        ),
    ]
