# Generated by Django 3.2.12 on 2022-03-21 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycookbook', '0009_recipe_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFavoriteRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fav_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycookbook.recipe')),
            ],
        ),
    ]
