# Generated by Django 3.2.12 on 2022-03-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycookbook', '0011_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
