# Generated by Django 4.0.3 on 2022-03-14 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycookbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='created_by',
        ),
        migrations.AddField(
            model_name='recipe',
            name='owner',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='UserMyRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_my_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycookbook.recipe')),
            ],
        ),
    ]
